---
title: "Desc."
output:
  html_document:
    df_print: paged
---


## 주의! 

* 저는 여기 올린 분석의 전문가가 아닙니다. 내용의 오류가 있을 수 있고 지적은 언제든 환영합니다. anarinsk@gmail.com
* 데이터는 통계청 [마이크로데이터서비스](https://mdis.kostat.go.kr/) (MDIS)에서 다운받으실 수 있습니다. 

# How to use 

  * 가구구분, 소득종류, 구간소득을 각각 선택한다. 
  * "update!"를 누르면 해당 조건에 따른 계산 및 그림을 생성한다. 
  * "Download RAW": 계산에 활용한 원데이터를 다운로드 한다.   * "Download PCT": 백분위 구간을 할당하는 두가지 방법에 따라서 가구 고유 코드에 할당된 백분위 구간 레이블을 다운로드 한다. 
  

# 자료 생성 절차 및 주요 변수  

* MDIS에서 다운받은 자료를 2017년과 2018년 두 개 년도의 비교를 위해 가공했습니다.  
* 2017년 자료에서 1/4 분기 자료를 필터링하고 이를 2018년 1/4 분기 자료와 결합했습니다.  
* 2018년 소득값은 해당 분기의 GDP디플레이터를 적용해 보정했습니다. 
  (2017년 1분기 = 110.9, 2018년 1분기 = 111.8)

## 유의사항 

* MDIS에서 제공되는 원자료가 txt 파일이다. 
* 함께 제공되는 SAS나 SPSS의 스크립트를 통해 해당 소프트웨어의 데이터셋으로 생성할 수 있다. 개인적으로 왜 공공기관의 서비스가 이런 모양새로 제공되는지 이해하기 힘들다. 
* 확장자 sas 파일을 뜯어보면 변수들 어떤 이름으로 할당되는지 쉽게 알 수 있다. 
* 2017년 자료의 컬럼은 134개이고, 2018년 자료의 컬럼은 128개이다. 컬럼의 할당을 sas 스크립트에서 확인한 후, 분석을 위해서 같은 컬럼끼리 가지런하게 합쳤다. 
* 각 컬럼에 코딩된 숫자가 의미하는 바는 구체적인 내용 및 코딩방식은 MDIS를 직접 참고하라. * 분석에 활용한 몇 가지 변수는 아래 "주요변수" 섹션을 참고하라. 
* 해당 자료의 다운로드는 옆 패널의 "Download" 버튼을 누르면 된다. 

## 가중치 활용방식 

  1. type 1: 각 가구들을 하나로 간주하고 이를 줄세워 100 분위를 할당한다. 분위 내의 소득은 가중치를 고려해 가중 평균 혹은 가중 중간값을 활용한다. 
  2. type 2: 가중치가 해당 가구를 대표하는 규모라고 간주하여 해당 소득을 지닌 가구가 가중치 만큼 존재한다고 가정하고, 100 분위를 할당한다. 단, 이 경우 분위 내 평균 혹은 중간값은 별도의 가중치를 부여하지 않는다. 

## 주요 변수 

  1. V1: 년도 
  2. V2: 분기 코드 (데이터셋에서 삭제)
  3. V3: 가구 고유 코드
  4. V4: 가구 구분 (1: 근로자 가구, 2: 근로자 외 가구)
  5. V5: 가구 원수 
  6. V99: 가중치 (가중치에 대한 상세한 설명은 MDIS 참고)
  7. V100: 소득 
  8. V101: 경상소득 
  9. V102: 근로소득 
  10. V103: 가구주소득 
  
  소득 분류 관련은 [여기](https://eiec.kdi.re.kr/material/archive/concept/view.jsp?cc=00002000010000100005&cid=129) 참고하자. 